sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master

install:
  - mvn clean package -Dfabric8.skip -Dmaven.test.skip.exec

script:
  - mvn test

jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - antonin.stefanutti@gmail.com