spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb