camel:
  springboot:
    # The Camel context name
    name: CamelRestJpa
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /camel-rest-jpa/*

logging:
  level:
    root: INFO

management:
  # Binding health checks to a different port
  port: 8081

# Disable all management endpoints except but health checks
endpoints:
  enabled: false
  health:
    enabled: true

spring:
  # Spring JDBC configuration
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url:

# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
